### ISSUE TITLE
something is wrong,can you help me

### ISSUE THREAD

**Issue by 1247388421** [Yimi81/VLP2MSA#1]
Training epoch 1:   0%|                                                                                                                                                                  | 0/161 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    run()
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train.py", line 92, in run
    trainer.train()
  File "/root/VLP2MSA/base/base_trainer.py", line 86, in train
    result = self._train_epoch(epoch)
  File "/root/VLP2MSA/trainer/trainer.py", line 90, in _train_epoch
    pred, video_feat, text_feat, temp = self.model(data, bTrain=True)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/VLP2MSA/model/model.py", line 146, in forward
    fusion_output = self.compute_fusion(text_features, video_embeddings, text_mask)
  File "/root/VLP2MSA/model/model.py", line 182, in compute_fusion
    fusion_output, pooled_output = self.fusion_transformer(concat_features)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/VLP2MSA/model/model_TVI.py", line 120, in forward
    embedding_output = self.transformer(embedding_output, extended_attention_mask)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/VLP2MSA/model/model_TVI.py", line 56, in forward
    return self.resblocks((x, attn_mask))[0]
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/VLP2MSA/model/model_TVI.py", line 43, in forward
    x = x + self.attention(self.ln_1(x), attn_mask)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/VLP2MSA/model/model_TVI.py", line 16, in forward
    ret = super().forward(x.type(torch.float32))
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 171, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "/root/miniconda3/envs/vlp2msa/lib/python3.7/site-packages/torch/nn/functional.py", line 2205, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Given normalized_shape=[768], expected input with shape [*, 768], but got input of size[9, 2, 512]

**Comment by Yimi81** [comment]
change https://github.com/Yimi81/VLP2MSA/blob/dec24447466709f5340724749087428597e52b7b/configs/mosi.json#L29C18-L29C29 to 512

**Comment by webbrain-one** [comment]
Hi! Sorry about the issue. I opened [PR #2](https://github.com/Yimi81/VLP2MSA/pull/2), which fixes the shape mismatch in the fusion transformer by making sure the embeddings are 768-dimensional before the LayerNorm, so training should proceed normally.
